version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

#  cache:
#    image: redis:6.2-alpine
#    restart: always
#    ports:
#      - '6379:6379'
#    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
#    volumes:
#      - cache:/data
#
#  minio:
#    container_name: minio
#    image: minio/minio:latest
#    restart: always
#    ports:
#      - '9000:9000'
#      - '9001:9001'
#    environment:
#      MINIO_ROOT_USER: kadir123456
#      MINIO_ROOT_PASSWORD: kadir123456
#    volumes:
#      - minio-data:/data
#    command: server /data --console-address ":9001"

volumes:
  db:
    driver: local
#  cache:
#    driver: local
#  minio-data:
#    driver: local
