name: Auto Pull on Server

on:
  push:
    branches:
      - master

jobs:
  auto-pull:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Auto Pull on Server
      run: git pull origin master
      working-directory: /home/kimvardev/test/todo-app
