name: SSH Connect

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH }}" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa.pub
        cat ~/.ssh/id_rsa.pub

        ssh-keyscan -H ${{ secrets.HOST }}  >> ~/.ssh/known_hosts
        cat ~/.ssh/known_hosts

    - name: SSH Connection
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} 

    - name: Update Server
      run: |
        cd /home/kmvar/hooks/todo-app 
        git pull origin master
        npm install 
        npm run build
