name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: connect ssh
      run: |
        ssh-keyscan -H 192.168.35.16 >> ~/.ssh/known_hosts
        ssh kimvardev@192.168.35.16 "whoami"
