
name: Otomatik Pull ve Sunucu Güncelleme

on:
  push:
    branches:
      - master

jobs:
  update-server:
    runs-on: ubuntu-latest

    steps:
      - name: Repo
        uses: actions/checkout@v3 

      - name: SSH ile Sunucuya Bağlan ve Güncelle
        run: |
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 
          git remote -v
          cd /Users/panates/Documents/personal/test/todo-app
          git checkout master
          git pull
          npm install
          npm run build
