name: Update Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Update Server
      run: |
        ssh -v -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} ssh -p ${{ secrets.SERVER_PORT }} sshpass -p ${{ secrets.SERVER_PASSWORD }} 'cd /home/kmvar/test/todo-app && git checkout testyaml && git pull'
      env:
        SERVER_PASSWORD: ${{ secrets.SERVER_HOST }}
        SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
        SERVER_HOST: ${{ secrets.SERVER_PASSWORD }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
