
name: Otomatik Pull ve Sunucu Güncelleme

on:
  push:
    branches:
      - master

jobs:
  update-server:
    runs-on: ubuntu-latest

    steps:
      - name: Repo 
        uses: actions/checkout@v3 
      
      - name: multiple command
        uses: appleboy/ssh-action@v1.0.0
        with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USERNAME }}
            password: ${{ secrets.SERVER_PASSWORD }}
            script: | 
                cd /Users/panates/Documents/personal/test/todo-app
                git checkout master
                git pull
                npm install
                npm run build
