
name: Otomatik Pull ve Sunucu Güncelleme

on:
  push:
    branches:
      - master

jobs:
  update-server:
    runs-on: ubuntu-latest

    steps:
      - name: Repo
        uses: actions/checkout@v3 
      
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Connect to server
        run: ssh -t ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 

      - name: testler
        run: |
          cd /Users/panates/Documents/personal/test/todo-app
          git checkout master
          git pull
          npm install
          npm run build
