
name: Otomatik Pull ve Sunucu Güncelleme

on:
  push:
    branches:
      - master

jobs:
  update-server:
    runs-on: ubuntu-latest

    steps:
      - name: Repo 
        uses: actions/checkout@v3 
      
      - name: Update Server
        run: |
          ssh -vvv ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'cd /Users/panates/Documents/personal/test/todo-app && git pull origin dev && npm install && npm run build' > update_logs.txt
        env:
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
