name: Auto Pull on Server

on:
  push:
    branches:
      - master

jobs:
  auto-pull:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Auto Pull on Server
      run: ssh kimvardev@192.168.35.16 "cd /home/kimvardev/test/todo-app && git pull origin master"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
