name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.1
      with:
        host: 192.168.35.16
        username: kimvardev
        password: Qwe1Asd2-
        port: 22
        timeout: 50s
        debug: true
        script: whoami
