name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: connect ssh
      run: ssh -vvv ${{ secrets.USERNAME }}@${{ secrets.HOST }} sshpass -p ${{ secrets.PASSWORD }}
    - name: test
      run: ls
