name: Update Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    
    - name: Update Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /Users/panates/Documents/personal/test/todo-app
          git checkout dev
          git pull 
          npm install
          npm run build

    - name: Check for Errors
      id: check-errors
      run: |
        if [ $? -ne 0 ]; then
          echo "::set-output name=status::failure"
          echo "Error: Server update or build failed."
          exit 1
        else
          echo "::set-output name=status::success"
          echo "Server update and build successful."
        fi

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Notify Status
      if: ${{ needs.deploy.outputs['check-errors.status'] == 'failure' }}
      run: echo "Server update or build failed. Please check the logs."
    - name: Notify Success
      if: ${{ needs.deploy.outputs['check-errors.status'] == 'success' }}
      run: echo "Server update and build successful."
