name: Update Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update Server
      run: |
        ssh ubuntu@localhot sshpass -p "${{ secrets.HOST }}" 'cd /home/ubuntu/Documents/todo-app && git pull origin master && npm install && npm run build' > update_logs.txt

    - name: Check for Errors
      id: check-errors
      run: |
        if [ $? -ne 0 ]; then
          echo "::set-output name=status::failure"
          echo "Error: Server update or build failed."
          exit 1
        else
          echo "::set-output name=status::success"
          echo "Server update and build successful."
        fi

  notify:
    needs: deploy
    runs-on: ubuntu-20.04
    steps:
    - name: Notify Status
      if: ${{ needs.deploy.outputs['check-errors.status'] == 'failure' }}
      run: echo "Server update or build failed. Please check the logs."
    - name: Notify Success
      if: ${{ needs.deploy.outputs['check-errors.status'] == 'success' }}
      run: echo "Server update and build successful."
