name: Deploy to SSH Server

on:
  push:
    branches:
      - master  # Değişiklik olduğunda çalışacak branch adını buraya ekleyin

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOST }}

      - name: Deploy to SSH Server
        run: |
          ssh -v -v -v -p 22 kmvar@192.168.35.68 "whoami"
