name: Update Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    
    - uses: actions/checkout@v3
    - uses: webfactory/ssh-agent@v0.8.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Update Server
      run: |
        cd /home/ubuntu/Documents/todo-app && git pull origin master && npm install && npm run build > update_logs.txt
    #   env:
    #     SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}

    - name: Check for Errors
      id: check-errors
      run: |
        if [ $? -ne 0 ]; then
          echo "::set-output name=status::failure"
          echo "Error: Server update or build failed."
          exit 1
        else
          echo "::set-output name=status::success"
          echo "Server update and build successful."
        fi

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Notify Status
      if: ${{ needs.deploy.outputs['check-errors.status'] == 'failure' }}
      run: echo "Server update or build failed. Please check the logs."
    - name: Notify Success
      if: ${{ needs.deploy.outputs['check-errors.status'] == 'success' }}
      run: echo "Server update and build successful."
